### ISSUE TITLE
[🐛BUG] Usage of Time command returns Standard Time, not Daylight time (when in effect)

### ISSUE THREAD

**Issue by The120thWhisper** [Xeevis/EmberBot#2]
When using the Time command to grab time for the next Chief Chat (as of this writing), it was noticed that the time zone of PDT was still returning the PST offset. 

Pacific time is currently in Daylight Saving time, which changes the UTC offset to -7, instead of the "standard" -8. 

This is leading to inaccurate Time responses by emberbot in Discord, but only by the one hour. 

further explanation in the screenshot attached with an example. 

![Time zone off](https://user-images.githubusercontent.com/5464250/116177273-868a6000-a6e1-11eb-9faa-453ebaf24ca0.png)

**Comment by Xeevis** [comment]
Thanks for the report. I've rewrote the command to take timezone abbreviation as hardcoded value. Until now it was supposed to be automatic depending on what is observed rather than what is written. This wasn't ideal to begin with and now was broken completely as every country observes daylight saving differently and we can't make assumptions what user has meant. But it also means that user may make a mistake by using wrong one for any given time. Guess it's something we can live with.

![image](https://user-images.githubusercontent.com/5835044/116294867-bea0aa00-a798-11eb-9ec4-1b54b20fd62a.png)
